[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev                ; ← DevKitC WROOM 32U ✓
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
board_build.partitions = default_16MB.csv
lib_deps = 
    arduino-libraries/ArduinoBLE
build_flags = 
    -DCORE_DEBUG_LEVEL=0
