[env:esp32dev]
platform = espressif32@6.7.0
board = esp32-devkitc-32e
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv
lib_deps = 
    ESP32 BLE Arduino
upload_protocol = esptool
