[env:esp32dev]
platform = espressif32@6.7.0
board = esp32-devkitc-wroom  ; ← DevKitC WROOM 32U ✓
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps = 
    ESP32 BLE Arduino
    ; Tambah library lain kalau perlu
build_flags = 
    -DCORE_DEBUG_LEVEL=0
